### ISSUE TITLE
Failed to establish TLS connection with client

### ISSUE THREAD

**Issue by piokto** [zu1k/good-mitm#46]
```
thread 'tokio-runtime-worker' panicked at 'Failed to establish TLS connection with client: Custom { kind: UnexpectedEof, error: "tls handshake eof" }', /project/crates/core/src/mitm.rs:142:30
thread 'tokio-runtime-worker' panicked at 'Failed to establish TLS connection with client: Custom { kind: UnexpectedEof, error: "tls handshake eof" }', /project/crates/core/src/mitm.rs:142:30
thread 'tokio-runtime-worker' panicked at 'Failed to establish TLS connection with client: Custom { kind: InvalidData, error: CorruptMessage }', /project/crates/core/src/mitm.rs:142:30
thread 'tokio-runtime-worker' panicked at 'Failed to establish TLS connection with client: Custom { kind: InvalidData, error: CorruptMessage }', /project/crates/core/src/mitm.rs:142:30
thread 'tokio-runtime-worker' panicked at 'Failed to establish TLS connection with client: Custom { kind: InvalidData, error: CorruptMessage }', /project/crates/core/src/mitm.rs:142:30
[2022-09-21T08:44:24Z INFO  g
```

**Comment by zu1k** [comment]
无法与客户端建立 TLS 连接，大概率因为客户端不信任证书。

1. 检查操作系统或浏览器是否信任 Good-MITM 证书
2. 检查是否有 SSL Pinning

**Comment by piokto** [comment]
使用拦截时无法对http进行访问

**Comment by zu1k** [comment]
> 使用拦截时无法对http进行访问

请提供更详细的信息

**Comment by zu1k** [comment]
请附上你的规则文件，日志使用源码格式

**Comment by zu1k** [comment]
无法复现，测试无任何问题，请自行检查
