### ISSUE TITLE
[Bug]  ERROR good_mitm_core::mitm 

### ISSUE THREAD

**Issue by libuke** [zu1k/good-mitm#67]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经仔细看过 [Documentation](https://good-mitm.zu1k.com/) 并无法自行解决问题 I have read the [documentation](https://good-mitm.zu1k.com/) and was unable to solve the issue. 

### Version

0.42

### What OS are you seeing the problem on?

macOS

### Rule file

```yaml
- name: "redirect"
  filter:
    domain-suffix: 'google.cn'
  action:
    redirect: "https://hao123.com"
- name: "reject CSDN"
  filter:
    domain-keyword: 'csdn'
  action: reject
- name: "modify response body plain"
  filter:
    domain: '126.com'
  action:
    modify-response:
      body: "Hello 126.com, from Good-MITM"
```

### log

```shell
...
[2023-07-20T17:15:53Z ERROR good_mitm_core::mitm] Tls accept failed: tls handshake eof
[2023-07-20T17:15:53Z ERROR good_mitm_core::mitm] Tls accept failed: peer is incompatible: SignatureAlgorithmsExtensionRequired
[2023-07-20T17:15:54Z ERROR good_mitm_core::mitm] Tls accept failed: tls handshake eof
[2023-07-20T17:15:54Z ERROR good_mitm_core::mitm] Tls accept failed: tls handshake eof
[2023-07-20T17:15:54Z ERROR good_mitm_core::mitm] Tls accept failed: peer is incompatible: SignatureAlgorithmsExtensionRequired
[2023-07-20T17:15:54Z ERROR good_mitm_core::mitm] Tls accept failed: tls handshake eof
[2023-07-20T17:15:54Z ERROR good_mitm_core::mitm] Tls accept failed: tls handshake eof
[2023-07-20T17:15:54Z ERROR good_mitm_core::mitm] Tls accept failed: peer is incompatible: SignatureAlgorithmsExtensionRequired
...
```

### Description

good-mitm 部署在openwrt中 (mac部署有同样的错误)
客户端设备为：mac 、ios

操作步骤：系统设置 --> 点击头像
结论：
- 家庭共享显示为不可用 
- 设备列表无法显示 
- good-mitm 控制台出现大量的tls错误

通过Proxyman 抓包发现会大量请求 https://gateway.icloud.com 域名
使用的配置文件中并未对gateway.icloud.com做HTTPS解密处理
(通过测试小火箭、Proxyman也无法对gateway.icloud.com进行HTTPS解密 )

 good-mitm能否跳过指定域名？

**Comment by zu1k** [comment]
目前如果使用 http 代理可以筛选域名，透明代理暂时还未实现域名筛选

**Comment by zu1k** [comment]
try the latest master branch

**Comment by libuke** [comment]
> try the latest master branch

感谢回复，我来试试

**Comment by libuke** [comment]
> try the latest master branch

我使用cargo build命令编译 操作系统为macos

当有http请求时报错
[2023-07-21T04:49:58Z INFO  good_mitm] CA Private key use: ca/private.key
[2023-07-21T04:49:58Z INFO  good_mitm] CA Certificate use: ca/cert.crt
[2023-07-21T04:49:58Z INFO  good_mitm] Http Proxy listen on: http://127.0.0.1:34567
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ParseError(34, TrailingBackslash)', crates/rule/src/cache.rs:10:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
...

**Comment by zu1k** [comment]
> thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ParseError(34, TrailingBackslash)', crates/rule/src/cache.rs:10:33

caused by a bad regular expression

**Comment by libuke** [comment]
> > thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ParseError(34, TrailingBackslash)', crates/rule/src/cache.rs:10:33
> 
> caused by a bad regular expression

还是不行，稳定复现
复现步骤：系统设置 -> (头像 -> icloud)(返回 -> icloud.  循环几次) 
结论：一个名为cloudd的应用程序疯狂请求https://gateway.icloud.com
疯狂提示：[2023-07-21T05:22:59Z ERROR good_mitm_core::mitm] Tls accept failed: tls handshake eof
[2023-07-21T05:22:59Z ERROR good_mitm_core::mitm] Tls accept failed: peer is incompatible: SignatureAlgorithmsExtensionRequired

// 貌似这玩意有点特殊，我用proxyman抓包添加对该域名的https解密后就疯狂的请求（错误信息：SSL 握手失败），关闭https解密后就正常请求，不过状态一直处于等待中

浏览器访问网页目前一切正常，就是这玩意容易疯狂请求疯狂报错根本看不到good-mitm正常输出信息

**Comment by zu1k** [comment]
If the request doesn't have an SNI record, then there's nothing we can do to filter it, you can only do checks at the upper layers, e.g. to avoid propagating that type of traffic to Good-MITM.

**Comment by libuke** [comment]
> If the request doesn't have an SNI record, then there's nothing we can do to filter it, you can only do checks at the upper layers, e.g. to avoid propagating that type of traffic to Good-MITM.

感谢，目前用AdguardHome重写应答的IP，80 443流量转发至34567的时候做了IP判断。

**Comment by zu1k** [comment]
I don't have a Mac, so I can't capture the packets to see what's going on.
It seems that `gateway.apple.com` is special, either the client has SSL pinning, or it has a special tls parameter (signature algorithm), or there is no SNI.
